default: &default
  adapter: mysql2
  encoding: utf8
  database: your_database_name
  pool: 5
  host: 127.0.0.1
  username: root
  password: 
  slave:
    host: 127.0.0.1 

development:
  <<: *default


test: &test
  adapter: mysql2
  encoding: utf8
  database: your_database_name_test
  pool: 5
  host: 127.0.0.1
  username: root
  password: 
  slave:
    host: 127.0.0.1 
